; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RandomChooose"
#define MyAppVersion "5.0.0"
#define MyAppPublisher "MDTeam"
#define MyAppExeName "RandomChoose.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{65DFB0CC-9D78-47C0-9747-41A96D7ACB78}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=D:\RandomChoose\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\RandomChoose\target\release\deps\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\bytemuck_derive-a052673b69da4ac6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\bytemuck_derive-a052673b69da4ac6.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\com_macros-1c52b683f3942ff7.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\com_macros-1c52b683f3942ff7.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\futures_macro-d4437e43252fd2e9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\futures_macro-d4437e43252fd2e9.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\palette_derive-6071f8c8ee72839d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\palette_derive-6071f8c8ee72839d.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\phf_macros-dd1b53bc093cdcdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\phf_macros-dd1b53bc093cdcdf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\RandomChoose.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\RandomChoose.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\thiserror_impl-6015043cfe9d8115.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\thiserror_impl-6015043cfe9d8115.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\tracing_attributes-1241b7ece3350464.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\tracing_attributes-1241b7ece3350464.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\zerocopy_derive-f398fe4e921abe89.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\target\release\deps\zerocopy_derive-f398fe4e921abe89.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\RandomChoose\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

